[profile.default]
solc_version = "0.8.20"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@chainlink/contracts/=lib/chainlink/contracts/',
]
